config/routes.rb
Rails.application.routes.draw do

  root 'courses#index'
  get 'courses/new', to: 'courses#new'
  get 'about', to: 'pages#about'
  resources :students, except: [:destroy]
  get 'login', to: 'logins#new'
  post 'login', to:'logins#create'
  delete 'logout', to: 'logins#destroy'
  post 'course_enroll', to: 'student_courses#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true, length: {minimum: 5, maximum:50}
  validates :short_name, presence: true, length: {minimum: 3, maximum:20}
  validates :description, presence: true, length: {minimum: 20, maximum:300}
  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {minimum: 5, maximum:50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i  
  validates :email, presence: true, length: { maximum: 105 },            
                     uniqueness: { case_sensitive: false },            
                       format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :require_user

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:notice] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    skip_before_action :require_user
    
    def index
        @courses = Course.all
    end

    def new
  
    end
    
  end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
		skip_before_action :require_user, only: [:new, :create]

		def new
				
		end

		def create
			student= Student.find_by(email: params[:logins][:email].downcase)
			if student && student.authenticate(params[:logins][:password])
				session[:student_id] = student.id
				flash[:notice] = "You have successfully logged in"
				redirect_to student
			else
				flash.now[:notice] = "Something was wrong with your login info"
				render 'new'
			end
		end

		def destroy
			session[:student_id] = nil
			flash[:notice] = "You have successfully logged out"
			redirect_to root_path
		end
		
	end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_user

  def about

  end
  
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController

  def create
    course_to_add = Course.find(params[:course_id])
    unless current_user.courses.include?(course_to_add)
      StudentCourse.create(course: course_to_add, student: current_user)
      flash[:notice] = "You have successfully enrolled in #{course_to_add.name}."
      redirect_to current_user
    else
      flash[:notice] = "Something was wrong with your enrollment"
      redirect_to root_path
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]
  before_action :set_student, only: [:show, :edit, :update]
  before_action :require_same_student, only: [:edit, :update]

  def index
    @students = Student.all
  end

  def show
    
  end

  def new
    @student = Student.new
  end

  def create
    @student= Student.new(student_params)
    if @student.save
      flash[:notice]="You have successfully signed up"
      redirect_to @student
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update
    
    if(@student.update(student_params))
      flash[:notice]="You have successfully updated your profile"
      redirect_to @student
    else
      render 'edit'
    end

  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end

  def set_student
    @student= Student.find(params[:id])
  end

  def require_same_student
    if current_user != @student
      flash[:notice] = "You could only edit your own profile"
      redirect_to student_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def session_link
    if (logged_in?) 
      link_to "logout", logout_path, method: :delete
    else
      link_to "login", login_path
    end
  end
end

app/views/courses/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align"> Course listing </h3>
  </div>
</div>

<div class="row">
  <% @courses.each do |course| %>
    <div class="col s12 m6">
      <div class="card blue-grey lighten-1">
        <div class="card-content white-text">
          <span class="card-title"><%= course.short_name %>: <%= course.name %></span>
          <p><%= course.description %></p>
        </div>
        <div class="card-action">
          <% if logged_in? && !(current_user.courses.include?(course)) %>
            <%= link_to "Enroll", course_enroll_path(course_id: course.id), method: :post %>
          <% end %>
          <a href="#">Info</a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/new.html.erb
<h1> new course page </h1>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">My Uni App</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Information</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact Us</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2014 Copyright Text
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<header>
  <ul id="dropdown1" class="dropdown-content">
    <li><%= session_link %></li>
    <% if logged_in? %>
    <li><%= link_to "Profile", student_path(current_user) %></li>
    <% end %>
  <li class="divider"></li>
  <li><a href="#!">three</a></li>
  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <li><%= session_link %></li>
    <% if logged_in? %>
      <li><%= link_to "Profile", student_path(current_user) %></li>
    <% end %>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>
  <nav>
    <div class="container">
      <div class="nav-wrapper">
        <%= link_to "My University", root_path, class: "brand-logo right" %>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>

        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><%= link_to "Courses", root_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Students", students_path %></li>
          <% end %>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>

        </ul>
        <ul class="sidenav" id="mobile-demo">
        <li><%= link_to "Courses", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Students", students_path %></li>
        <% end %>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>              
        </ul>
      </div>
    </div>
  </nav>
  <% flash.each do |key, message| %>
    <div class="container">
      <div class="row signup-form">
        <div class="col s12 m12 l12">
          <div class="card-panel red lighten-2" id="fade-out-target">
            <span class="white-text">
              <%= message %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    
    <%= render 'layouts/footer' %>
      
  </body>
</html>

app/views/logins/new.html.erb
<div class="container">
  <div class="row center signup-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header">Log in</h3>
        <div class="row">
          <%= form_for :logins, html: {class: "col s12" } do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%=f.email_field :email, placeholder: "Enter your email address", autofocus:true %>
                <%= f.label :email %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%=f.password_field :password, placeholder: "Enter your password" %>
                <%= f.label :password, class:"active" %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.button'<i class="material-icons right">arrow_forward</i>Log in'.html_safe, class:"btn waves-effect waves-light btn" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<h1> about pagee </h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container">
    <div class="row signup-form">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <strong><%= pluralize(obj.errors.count, "error") %></strong>
            prohibited your profile from being created
            <ul>
              <% @student.errors.full_messages.each do |message| %>
                <li><%= message %>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>

<div class="container">
  <div class="row center signup-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header"><%= @student.new_record? ? "Sign up" : "Edit your profile" %></h3>
        <div class="row">
          <%= form_for @student, html: {class: "col s12" } do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder: "Enter your full name", autofocus:true %>
                <%= f.label :name %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%=f.email_field :email, placeholder: "Enter your email address" %>
                <%= f.label :email, class:"active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%=f.password_field :password, placeholder: "Choose a password" %>
                <%= f.label :password, class:"active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%=f.password_field :password_confirmation, placeholder: "Confirm your password" %>
                <%= f.label :password_confirmation, class:"active"  %>
              </div>
            </div>
            


            <div class="row">
              <div class="input-field col s12">
                <%= f.button( @student.new_record? ? '<i class="material-icons right">arrow_forward</i>Sign up'.html_safe : '<i class="material-icons right">arrow_forward</i>Submit changes'.html_safe, class:"btn waves-effect waves-light btn") %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align"> Students Directory </h3>
  </div>
</div>

<div class="row">
  <% @students.each do |student| %>
    <div class="col s12 m6">
      <div class="card red lighten-3">
        <div class="card-content white-text">
          <span class="card-title">Name: <%= student.name %></span>
          <p>Email: <%= student.email %></p>
          <p>Course Enrollments: none</p>
        </div>
        <div class="card-action">
          <%= link_to "View_profile", student_path(student) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="row signup-form">
  <div class="col s12 m6">
    <div class="card red lighten-3">
      <div class="card-content white-text">
        <span class="card-title">Name: <%= @student.name %></span>
        <p>Email: <%= @student.email %></p>
        <p>Course Enrollments: 
          <% if @student.courses.empty? %> 
           None
          <% else %>
            <ul>
              <% @student.courses.each do |course| %>
                <li><%=course.name %>
              <% end %>
            </ul>
          <% end %>
        </p>
      </div>
    </div>
    <% if current_user == @student %>
     <%= link_to '<i class="material-icons right">create</i>Edit your profile'.html_safe, edit_student_path(@student), class:"waves-effect waves-light btn" %>
    <% end %>
  </div>
</div>